eureka:   #Configuration for creating User service as a client
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true # this property is by default true just added for learning purpose
    register-with-eureka: true # this property is by default true just added for learning purpose
    service-url:
      defaultZone: http://localhost:8761/eureka
